# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=800']
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools==57.4.9
          - types-python-dateutil==2.8.9
          - types-python-slugify==5.0.3
          - types-pyyaml==6.0.8
          - types-requests==2.25.1
        args: [--ignore-missing-imports]
